version: '3.8'

services:
  postgres:
    image: postgres:16.2  # Specify the desired version here
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: movie-ticket_database
      POSTGRES_USER: iamgovindthakur
      POSTGRES_PASSWORD: iamgovindthakur
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#docker-compose -f postgres-docker-compose.yaml up -d

