version: '3.8'

services:
  postgres:
    image: postgres:16.2  # Specify the desired version here
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

#docker-compose -f postgres-docker-compose.yaml up -d

